import type { CompetitorType, ProductCategory, RegulationTheme } from "@prisma/client";

export const countrySeed = [
  {
    name: "Netherlands",
    region: "Western Europe",
    marketAttractivenessScore: 84,
    horecaDensityScore: 78,
    sustainabilityMaturityScore: 88,
    regulatoryComplexityScore: 62,
    easeOfEntryScore: 81,
    logisticsFitScore: 79,
    willingnessToPaySignalScore: 72,
    priorityMarket: true,
    notes:
      "Good pilot geography with compact buyer clusters, relatively fast logistics from EU ports, and strong sustainability language in horeca procurement.",
    recommendationSummary:
      "Best balance of sustainability maturity, manageable market size, and good pilot potential.",
  },
  {
    name: "Germany",
    region: "Western Europe",
    marketAttractivenessScore: 80,
    horecaDensityScore: 82,
    sustainabilityMaturityScore: 83,
    regulatoryComplexityScore: 70,
    easeOfEntryScore: 68,
    logisticsFitScore: 75,
    willingnessToPaySignalScore: 69,
    priorityMarket: true,
    notes:
      "Large addressable base across chain cafés, corporate catering, and hotels, but buyers expect stronger documentation and a more structured go-to-market motion.",
    recommendationSummary:
      "Large opportunity but more operationally complex than the Netherlands.",
  },
  {
    name: "Belgium",
    region: "Western Europe",
    marketAttractivenessScore: 73,
    horecaDensityScore: 65,
    sustainabilityMaturityScore: 76,
    regulatoryComplexityScore: 60,
    easeOfEntryScore: 77,
    logisticsFitScore: 80,
    willingnessToPaySignalScore: 66,
    priorityMarket: false,
    notes:
      "Useful Benelux adjacency play with comparable buyer needs, though the market is smaller and slightly less urgent for a first pilot.",
    recommendationSummary:
      "Useful secondary Benelux comparison market with moderate complexity.",
  },
  {
    name: "United Kingdom",
    region: "Northern Europe",
    marketAttractivenessScore: 75,
    horecaDensityScore: 79,
    sustainabilityMaturityScore: 80,
    regulatoryComplexityScore: 74,
    easeOfEntryScore: 58,
    logisticsFitScore: 63,
    willingnessToPaySignalScore: 70,
    priorityMarket: false,
    notes:
      "Buyer demand is real, but import handling, market separation, and extra compliance process make it a heavier first-entry market.",
    recommendationSummary:
      "Attractive demand, but separate import/compliance handling makes it less attractive as first expansion market for this prototype.",
  },
];

export const interviewSeed = [
  {
    companyName: "Canal Roast Amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    businessType: "Independent specialty café",
    numberOfLocations: 2,
    currentSupplierType: "Local horeca wholesaler",
    sustainabilityImportance: 5,
    priceSensitivity: 3,
    opennessToAlternativeSuppliers: 4,
    painPoints: ["inconsistent eco claims", "high prices for premium packaging", "limited proof from suppliers"],
    keyQuote:
      "We want sustainable packaging, but we cannot spend double without being able to justify it.",
    currentProductsBought: ["cups", "lids", "napkins", "stirrers"],
    willingnessToPayNotes: "Moderate premium accepted if quality and proof are strong.",
    contactStatus: "Warm lead",
    summaryInsight: "Proof-backed mid-premium products are more acceptable than premium products with vague claims.",
  },
  {
    companyName: "North Bean Utrecht",
    city: "Utrecht",
    country: "Netherlands",
    businessType: "Café + takeaway",
    numberOfLocations: 1,
    currentSupplierType: "Regional cash-and-carry wholesaler",
    sustainabilityImportance: 4,
    priceSensitivity: 4,
    opennessToAlternativeSuppliers: 3,
    painPoints: ["soggy paper straws", "unreliable compostability claims"],
    keyQuote: "If the straw fails in iced drinks, the sustainability story doesn’t matter.",
    currentProductsBought: ["straws", "cups", "lids"],
    willingnessToPayNotes: "Would pay slightly more if product performance is proven.",
    contactStatus: "Interview completed",
    summaryInsight: "Operational quality is the gating factor for adoption in smaller takeaway-heavy outlets.",
  },
  {
    companyName: "Workbrew Offices Rotterdam",
    city: "Rotterdam",
    country: "Netherlands",
    businessType: "Office pantry supplier",
    numberOfLocations: 5,
    currentSupplierType: "National office-services wholesaler",
    sustainabilityImportance: 4,
    priceSensitivity: 3,
    opennessToAlternativeSuppliers: 5,
    painPoints: ["needs simple procurement comparison", "limited supplier standardization"],
    keyQuote: "Our buyers need one sheet that compares proof, price, and logistics in minutes.",
    currentProductsBought: ["cups", "napkins", "cutlery", "food containers"],
    willingnessToPayNotes: "Open to switching if procurement friction is lower.",
    contactStatus: "Follow-up requested",
    summaryInsight: "Comparison tooling itself is part of the product value for procurement-led segments.",
  },
  {
    companyName: "Green Fork Deli Amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    businessType: "Fast casual lunch",
    numberOfLocations: 3,
    currentSupplierType: "Local sustainable packaging reseller",
    sustainabilityImportance: 4,
    priceSensitivity: 4,
    opennessToAlternativeSuppliers: 4,
    painPoints: ["takeaway bowls too expensive", "not enough data on coatings"],
    keyQuote: "We need fiber bowls that do not wreck our margins.",
    currentProductsBought: ["bowls", "food containers", "napkins"],
    willingnessToPayNotes: "Needs sharper pricing for lunch formats, especially bowls.",
    contactStatus: "Pipeline",
    summaryInsight: "Meal-format packaging is commercially attractive if price can stay within current spend bands.",
  },
  {
    companyName: "Brunch District The Hague",
    city: "The Hague",
    country: "Netherlands",
    businessType: "Small chain café",
    numberOfLocations: 4,
    currentSupplierType: "Premium hospitality distributor",
    sustainabilityImportance: 5,
    priceSensitivity: 2,
    opennessToAlternativeSuppliers: 4,
    painPoints: ["wants premium presentation and proof"],
    keyQuote: "Presentation matters, but so does being able to defend our sustainability claims to guests.",
    currentProductsBought: ["cups", "lids", "napkins", "bowls"],
    willingnessToPayNotes: "Premium accepted if claims and presentation quality both hold up.",
    contactStatus: "Pilot candidate",
    summaryInsight: "Premium small chains are likely early adopters if the visual quality stays high.",
  },
  {
    companyName: "KoffieLab Eindhoven",
    city: "Eindhoven",
    country: "Netherlands",
    businessType: "Independent café",
    numberOfLocations: 1,
    currentSupplierType: "Discount horeca wholesaler",
    sustainabilityImportance: 3,
    priceSensitivity: 5,
    opennessToAlternativeSuppliers: 2,
    painPoints: ["price dominates", "open only if operational quality remains high"],
    keyQuote: "I can only switch if the price difference is small and staff don’t complain.",
    currentProductsBought: ["cups", "straws", "napkins"],
    willingnessToPayNotes: "Very limited premium tolerance.",
    contactStatus: "Low priority",
    summaryInsight: "Budget-sensitive independents are likely a later wave unless landed through strong comparison proof.",
  },
  {
    companyName: "Hotel Vale Breda",
    city: "Breda",
    country: "Netherlands",
    businessType: "Boutique hotel",
    numberOfLocations: 1,
    currentSupplierType: "Hospitality contract supplier",
    sustainabilityImportance: 4,
    priceSensitivity: 3,
    opennessToAlternativeSuppliers: 4,
    painPoints: ["wants standardized supplier info for procurement team"],
    keyQuote: "If the supplier data is standardized, we can move much faster internally.",
    currentProductsBought: ["napkins", "cups", "food containers"],
    willingnessToPayNotes: "Willing to pay a modest premium for reduced procurement effort.",
    contactStatus: "Qualified",
    summaryInsight: "Standardized product documentation reduces internal buyer friction in hotel groups.",
  },
  {
    companyName: "Bento Works Amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    businessType: "Office catering",
    numberOfLocations: 6,
    currentSupplierType: "Multi-category catering distributor",
    sustainabilityImportance: 5,
    priceSensitivity: 3,
    opennessToAlternativeSuppliers: 5,
    painPoints: ["wants cleaner way to compare product categories and supplier claims"],
    keyQuote: "We don’t need more supplier decks, we need a credible comparison layer.",
    currentProductsBought: ["bowls", "containers", "cutlery", "napkins"],
    willingnessToPayNotes: "Procurement team is open if comparison and proof quality improve.",
    contactStatus: "Pilot workshop scheduled",
    summaryInsight: "Office catering and pantry teams strongly value comparison-led procurement support.",
  },
];

export const competitorSeed: Array<{
  name: string;
  type: CompetitorType;
  geography: string;
  targetCustomers: string[];
  strengths: string[];
  weaknesses: string[];
  pricingSignal: string;
  hasScoringFeature: boolean;
  hasCertificationFeature: boolean;
  hasSourcingFeature: boolean;
  hasMarketplaceFeature: boolean;
  notes: string;
  differentiationNotes: string;
}> = [
  {
    name: "EcoSource Europe",
    type: "DIRECT",
    geography: "EU",
    targetCustomers: ["cafés", "restaurants", "office catering"],
    strengths: ["broad packaging catalog", "local logistics"],
    weaknesses: ["weak transparency in scoring"],
    pricingSignal: "Medium-high",
    hasScoringFeature: true,
    hasCertificationFeature: true,
    hasSourcingFeature: true,
    hasMarketplaceFeature: true,
    notes: "Feels like a broad catalog player rather than a structured decision-support platform.",
    differentiationNotes: "Green2B can win on evidence rigor and supply-side structuring across India-linked sourcing.",
  },
  {
    name: "PackProof SaaS",
    type: "ADJACENT",
    geography: "EU / UK",
    targetCustomers: ["procurement teams", "compliance managers"],
    strengths: ["compliance dashboards"],
    weaknesses: ["no sourcing marketplace"],
    pricingSignal: "Subscription enterprise",
    hasScoringFeature: true,
    hasCertificationFeature: true,
    hasSourcingFeature: false,
    hasMarketplaceFeature: false,
    notes: "Good systems layer, weak on supplier discovery and workflow.",
    differentiationNotes: "Green2B can bridge sourcing plus practical buyer comparison instead of stopping at compliance.",
  },
  {
    name: "IndiaTrade Packaging Brokers",
    type: "INDIRECT",
    geography: "India to EU",
    targetCustomers: ["importers", "price-led horeca distributors"],
    strengths: ["price", "sourcing connections"],
    weaknesses: ["low sustainability rigor"],
    pricingSignal: "Low",
    hasScoringFeature: false,
    hasCertificationFeature: false,
    hasSourcingFeature: true,
    hasMarketplaceFeature: false,
    notes: "Broker model prioritizes price and relationships over proof quality.",
    differentiationNotes: "Green2B can convert brokered sourcing into a more trustworthy platform layer.",
  },
  {
    name: "PureChain Audit Partners",
    type: "ADJACENT",
    geography: "Global",
    targetCustomers: ["large corporates", "enterprise procurement"],
    strengths: ["high credibility"],
    weaknesses: ["slow and expensive"],
    pricingSignal: "High",
    hasScoringFeature: true,
    hasCertificationFeature: true,
    hasSourcingFeature: false,
    hasMarketplaceFeature: false,
    notes: "Strong assurance brand, weak fit for lighter-weight SME pilots.",
    differentiationNotes: "Green2B can offer faster, more usable scoring with enough rigor for pilot-stage buying.",
  },
  {
    name: "GreenShelf Marketplace",
    type: "INDIRECT",
    geography: "Benelux",
    targetCustomers: ["cafés", "small chains", "office buyers"],
    strengths: ["buyer-friendly marketplace"],
    weaknesses: ["shallow evidence verification"],
    pricingSignal: "Medium",
    hasScoringFeature: false,
    hasCertificationFeature: false,
    hasSourcingFeature: true,
    hasMarketplaceFeature: true,
    notes: "Marketplace UX is strong but claims depth is thin.",
    differentiationNotes: "Green2B should emphasize comparable evidence and transparent grade logic, not just browse-and-buy UX.",
  },
  {
    name: "CircularServe NL",
    type: "DIRECT",
    geography: "Netherlands",
    targetCustomers: ["cafés", "restaurants", "events"],
    strengths: ["local network and fast delivery"],
    weaknesses: ["limited cross-border supplier base"],
    pricingSignal: "Medium-high",
    hasScoringFeature: false,
    hasCertificationFeature: true,
    hasSourcingFeature: true,
    hasMarketplaceFeature: true,
    notes: "Local operator with speed advantage, but narrower sourcing story.",
    differentiationNotes: "Green2B can combine broader sourcing optionality with a more transparent assessment layer.",
  },
];

export const regulationSeed: Array<{
  country: string;
  productCategory: ProductCategory;
  theme: RegulationTheme;
  requirementTitle: string;
  description: string;
  businessImplication: string;
  requiredDocuments: string[];
  complexityScore: number;
  urgencyScore: number;
  notes: string;
}> = [
  {
    country: "Netherlands",
    productCategory: "TAKEAWAY_CUPS",
    theme: "PACKAGING",
    requirementTitle: "Recycled-content support for fiber cup claims",
    description: "Buyers increasingly expect documentary proof when cups are sold as partially recycled or low-impact.",
    businessImplication: "Cup suppliers should be ready with a recycled-content declaration before pilot outreach.",
    requiredDocuments: ["Material declaration", "Packaging spec sheet"],
    complexityScore: 56,
    urgencyScore: 72,
    notes: "Useful for buyer trust even when not a hard legal blocker in the demo context.",
  },
  {
    country: "Netherlands",
    productCategory: "STRAWS",
    theme: "PROOF",
    requirementTitle: "Compostability claim substantiation",
    description: "If a straw is presented as compostable, buyers expect the exact condition and supporting standard to be stated.",
    businessImplication: "Avoid vague eco marketing. State home versus industrial compostability clearly.",
    requiredDocuments: ["Compostability statement", "Product technical sheet"],
    complexityScore: 48,
    urgencyScore: 78,
    notes: "Especially important for takeaway cafés after prior supplier disappointments.",
  },
  {
    country: "Netherlands",
    productCategory: "FOOD_CONTAINERS",
    theme: "FOOD_CONTACT",
    requirementTitle: "Food-contact declaration for direct-contact containers",
    description: "Containers touching hot or greasy foods should be backed by a food-contact declaration.",
    businessImplication: "Containers without this proof will stall in buyer reviews.",
    requiredDocuments: ["Food-contact declaration", "Technical sheet"],
    complexityScore: 66,
    urgencyScore: 82,
    notes: "High value for office catering and deli use cases.",
  },
  {
    country: "Germany",
    productCategory: "BOWLS",
    theme: "LABELING",
    requirementTitle: "Clear disposal-language alignment for molded-fiber bowls",
    description: "Disposal or compostability messaging should match actual recovery pathways and buyer expectations.",
    businessImplication: "Simplified buyer-facing grade cards should avoid overclaiming disposal pathways.",
    requiredDocuments: ["Compostability support", "Material declaration"],
    complexityScore: 61,
    urgencyScore: 70,
    notes: "Messaging consistency matters as much as the claim itself.",
  },
  {
    country: "Germany",
    productCategory: "CUTLERY",
    theme: "IMPORT",
    requirementTitle: "Importer-ready batch traceability summary",
    description: "Import-focused buyers prefer a concise batch-traceability summary for wood and bamboo formats.",
    businessImplication: "Green2B should standardize a traceability section in supplier intake.",
    requiredDocuments: ["Traceability summary", "Shipment declaration"],
    complexityScore: 64,
    urgencyScore: 65,
    notes: "Not a formal legal reading in this demo, but a practical buyer expectation.",
  },
  {
    country: "Germany",
    productCategory: "TAKEAWAY_CUPS",
    theme: "WASTE",
    requirementTitle: "Producer responsibility data-readiness",
    description: "Cup suppliers should be able to explain pack weights and material composition for downstream reporting needs.",
    businessImplication: "Missing weight data weakens both scoring and market readiness.",
    requiredDocuments: ["Packaging weight sheet", "Product composition sheet"],
    complexityScore: 68,
    urgencyScore: 76,
    notes: "Operationally relevant for larger chains and wholesalers.",
  },
  {
    country: "Belgium",
    productCategory: "LIDS",
    theme: "PACKAGING",
    requirementTitle: "Material split disclosure for molded-fiber lids",
    description: "Buyers want clear disclosure of fiber content, coatings, and recycled packaging content.",
    businessImplication: "Lid products with clean mono-material narratives are easier to position.",
    requiredDocuments: ["Material split declaration", "Packaging spec sheet"],
    complexityScore: 44,
    urgencyScore: 58,
    notes: "Useful checklist item for Benelux pilots.",
  },
  {
    country: "Belgium",
    productCategory: "NAPKINS",
    theme: "CERTIFICATION",
    requirementTitle: "Fiber-origin proof for recycled-paper napkins",
    description: "Recycled or FSC-backed napkins should cite the basis of the claim.",
    businessImplication: "Straightforward win if the supplier already has a credible declaration.",
    requiredDocuments: ["FSC declaration", "Recycled-fiber declaration"],
    complexityScore: 35,
    urgencyScore: 50,
    notes: "Lower complexity but still useful for procurement trust.",
  },
  {
    country: "Belgium",
    productCategory: "FOOD_CONTAINERS",
    theme: "PROOF",
    requirementTitle: "PFAS-free and coating-free claim pack",
    description: "Containers marketed as PFAS-free or coating-free should include a plain-language declaration.",
    businessImplication: "Helps avoid later procurement escalation.",
    requiredDocuments: ["PFAS-free declaration", "Technical sheet"],
    complexityScore: 59,
    urgencyScore: 69,
    notes: "Relevant for bagasse and molded-fiber formats.",
  },
  {
    country: "United Kingdom",
    productCategory: "TAKEAWAY_CUPS",
    theme: "IMPORT",
    requirementTitle: "Importer document pack for hospitality packaging",
    description: "UK buyers expect a cleaner importer-facing document pack than EU buyers for pilot sourcing.",
    businessImplication: "Adds friction for a first market entry compared with Benelux.",
    requiredDocuments: ["Commercial invoice sample", "Country of origin declaration", "Product technical sheet"],
    complexityScore: 74,
    urgencyScore: 72,
    notes: "One reason UK is less attractive as the first target market.",
  },
  {
    country: "United Kingdom",
    productCategory: "BOWLS",
    theme: "FOOD_CONTACT",
    requirementTitle: "Food-contact scope note for hot-food bowls",
    description: "Bowls used with hot meals need a clear statement about intended use and limitations.",
    businessImplication: "Important for hospitality buyers who serve soups or hot grain bowls.",
    requiredDocuments: ["Food-contact declaration", "Use-condition note"],
    complexityScore: 63,
    urgencyScore: 74,
    notes: "Useful to include in supplier intake templates.",
  },
  {
    country: "United Kingdom",
    productCategory: "STRAWS",
    theme: "LABELING",
    requirementTitle: "Claim wording discipline for plastic-free messaging",
    description: "If a straw includes a liner or additive, buyer-facing messaging should avoid simplified plastic-free claims.",
    businessImplication: "Supports credibility and avoids overstatement in demos.",
    requiredDocuments: ["Material declaration", "Marketing claim note"],
    complexityScore: 57,
    urgencyScore: 68,
    notes: "Relevant to lined paper straw products.",
  },
];
