import type { ContactStage, ProductCategory } from "@prisma/client";

export const supplierSeed: Array<{
  supplierCode: string;
  name: string;
  country: string;
  city: string;
  website: string;
  primaryMaterials: string[];
  productCategories: string[];
  bcorpCertified: boolean;
  otherCertifications: string[];
  evidenceCompletenessScore: number;
  contactStage: ContactStage;
  reliabilityRating: number;
  notes: string;
  riskFlags: string[];
}> = [
  {
    supplierCode: "SUP-001",
    name: "EcoSip India Pvt Ltd",
    country: "India",
    city: "Pune",
    website: "ecosip.example",
    primaryMaterials: ["paper", "PLA", "bamboo fiber"],
    productCategories: ["straws", "cups"],
    bcorpCertified: true,
    otherCertifications: ["B Corp", "FSC supplier declaration"],
    evidenceCompletenessScore: 82,
    contactStage: "CONTACTED",
    reliabilityRating: 78,
    notes: "Strong early fit for drinks-service categories with comparatively better documentation than most India-based suppliers.",
    riskFlags: ["long-distance shipping", "lined paper claims need clear wording"],
  },
  {
    supplierCode: "SUP-002",
    name: "FiberNest Packaging LLP",
    country: "India",
    city: "Ahmedabad",
    website: "fibernest.example",
    primaryMaterials: ["bagasse", "molded fiber"],
    productCategories: ["bowls", "food containers"],
    bcorpCertified: false,
    otherCertifications: ["ISO-like quality declaration", "compostability declaration"],
    evidenceCompletenessScore: 71,
    contactStage: "QUALIFIED",
    reliabilityRating: 74,
    notes: "Commercially promising for meal formats but documentation needs tightening around coatings and proof quality.",
    riskFlags: ["PFAS-free evidence still partial"],
  },
  {
    supplierCode: "SUP-003",
    name: "BlueRoot Tableware Exports",
    country: "India",
    city: "Bengaluru",
    website: "blueroot.example",
    primaryMaterials: ["bamboo", "wood"],
    productCategories: ["cutlery", "stirrers"],
    bcorpCertified: false,
    otherCertifications: ["supplier attestation only"],
    evidenceCompletenessScore: 58,
    contactStage: "CONTACTED",
    reliabilityRating: 65,
    notes: "Interesting natural-material profile but weak in quantified sustainability data.",
    riskFlags: ["missing LCA-lite data", "limited traceability depth"],
  },
  {
    supplierCode: "SUP-004",
    name: "CircularLeaf Goods",
    country: "United Arab Emirates",
    city: "Dubai",
    website: "circularleaf.example",
    primaryMaterials: ["recycled paper", "coated board"],
    productCategories: ["cups", "lids"],
    bcorpCertified: false,
    otherCertifications: ["FSC-like claim pending verification"],
    evidenceCompletenessScore: 63,
    contactStage: "QUALIFIED",
    reliabilityRating: 68,
    notes: "Good mid-market option for drinkware formats, though claims need cleaner verification.",
    riskFlags: ["claim verification pending", "mid-range pricing pressure"],
  },
  {
    supplierCode: "SUP-005",
    name: "NoordEco Supplies BV",
    country: "Netherlands",
    city: "Rotterdam",
    website: "noordeco.example",
    primaryMaterials: ["recycled paper", "fiber", "molded pulp"],
    productCategories: ["cups", "lids", "napkins"],
    bcorpCertified: true,
    otherCertifications: ["B Corp", "FSC"],
    evidenceCompletenessScore: 91,
    contactStage: "PILOT",
    reliabilityRating: 87,
    notes: "Best-documented supplier in the seed set and likely benchmark reference for buyer-facing demos.",
    riskFlags: ["higher local pricing"],
  },
  {
    supplierCode: "SUP-006",
    name: "TerraServe UK Ltd",
    country: "United Kingdom",
    city: "Manchester",
    website: "terraserve.example",
    primaryMaterials: ["paper", "bagasse"],
    productCategories: ["napkins", "containers", "bowls"],
    bcorpCertified: false,
    otherCertifications: ["packaging declarations"],
    evidenceCompletenessScore: 76,
    contactStage: "QUALIFIED",
    reliabilityRating: 73,
    notes: "Solid mid-tier supplier with decent disclosure and shorter transport lanes into north-west Europe.",
    riskFlags: ["UK market complexity", "less premium design finish"],
  },
];

export const productSeed = [
  {
    productCode: "PROD-001",
    supplierName: "EcoSip India Pvt Ltd",
    productName: "EcoSip Classic Paper Straw",
    category: "STRAWS" as ProductCategory,
    targetSegment: "Cafés and takeaway drinks",
    unitPriceEur: 0.028,
    currency: "EUR",
    minimumOrderQuantity: 100000,
    leadTimeDays: 28,
    originCountry: "India",
    materialDescription: "FSC paper with thin PLA lining",
    renewableMaterialPercent: 86,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 8,
    plasticLining: true,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: false,
    packagingMaterial: "corrugated carton",
    packagingRecycledContentPercent: 75,
    packagingWeightGramsPer100Units: 42,
    productWeightGramsPer100Units: 95,
    estimatedCo2ePer1000Units: 11.2,
    estimatedWaterLitersPer1000Units: 92,
    transportMode: "sea",
    distanceKm: 7400,
    supplierDisclosureScore: 82,
    laborPolicyScore: 74,
    traceabilityScore: 68,
    evidenceStatus: "Mostly verified",
    notes: "Commercially strong baseline straw with decent proof pack, but lined-paper claims must stay precise.",
  },
  {
    productCode: "PROD-002",
    supplierName: "EcoSip India Pvt Ltd",
    productName: "EcoSip Bamboo Blend Straw",
    category: "STRAWS" as ProductCategory,
    targetSegment: "Premium cafés and hotels",
    unitPriceEur: 0.035,
    currency: "EUR",
    minimumOrderQuantity: 100000,
    leadTimeDays: 30,
    originCountry: "India",
    materialDescription: "Paper and bamboo fiber blend",
    renewableMaterialPercent: 94,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: true,
    packagingMaterial: "corrugated carton",
    packagingRecycledContentPercent: 80,
    packagingWeightGramsPer100Units: 39,
    productWeightGramsPer100Units: 101,
    estimatedCo2ePer1000Units: 9.1,
    estimatedWaterLitersPer1000Units: 104,
    transportMode: "sea",
    distanceKm: 7400,
    supplierDisclosureScore: 79,
    laborPolicyScore: 74,
    traceabilityScore: 72,
    evidenceStatus: "Mostly verified",
    notes: "Stronger sustainability story than the classic straw with slightly higher water intensity.",
  },
  {
    productCode: "PROD-003",
    supplierName: "FiberNest Packaging LLP",
    productName: "FiberNest Bagasse Bowl 750ml",
    category: "BOWLS" as ProductCategory,
    targetSegment: "Fast casual lunch and office catering",
    unitPriceEur: 0.122,
    currency: "EUR",
    minimumOrderQuantity: 50000,
    leadTimeDays: 32,
    originCountry: "India",
    materialDescription: "Molded bagasse bowl",
    renewableMaterialPercent: 96,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: false,
    packagingMaterial: "kraft carton",
    packagingRecycledContentPercent: 60,
    packagingWeightGramsPer100Units: 88,
    productWeightGramsPer100Units: 420,
    estimatedCo2ePer1000Units: 24.5,
    estimatedWaterLitersPer1000Units: 210,
    transportMode: "sea",
    distanceKm: 7600,
    supplierDisclosureScore: 67,
    laborPolicyScore: 63,
    traceabilityScore: 59,
    evidenceStatus: "Some evidence missing",
    notes: "Promising bowl offer, but supporting proof and end-of-life messaging are incomplete.",
  },
  {
    productCode: "PROD-004",
    supplierName: "FiberNest Packaging LLP",
    productName: "FiberNest PFAS-Free Meal Container",
    category: "FOOD_CONTAINERS" as ProductCategory,
    targetSegment: "Office catering and delis",
    unitPriceEur: 0.168,
    currency: "EUR",
    minimumOrderQuantity: 40000,
    leadTimeDays: 34,
    originCountry: "India",
    materialDescription: "Molded fiber container with PFAS-free claim",
    renewableMaterialPercent: 94,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: false,
    packagingMaterial: "corrugated carton",
    packagingRecycledContentPercent: 64,
    packagingWeightGramsPer100Units: 96,
    productWeightGramsPer100Units: 460,
    estimatedCo2ePer1000Units: 27.2,
    estimatedWaterLitersPer1000Units: 236,
    transportMode: "sea",
    distanceKm: 7600,
    supplierDisclosureScore: 70,
    laborPolicyScore: 63,
    traceabilityScore: 61,
    evidenceStatus: "Provisionally documented",
    notes: "Commercially attractive if PFAS-free proof becomes cleaner and easier to share.",
  },
  {
    productCode: "PROD-005",
    supplierName: "BlueRoot Tableware Exports",
    productName: "BlueRoot Bamboo Cutlery Set",
    category: "CUTLERY" as ProductCategory,
    targetSegment: "Office catering and delivery meals",
    unitPriceEur: 0.089,
    currency: "EUR",
    minimumOrderQuantity: 60000,
    leadTimeDays: 29,
    originCountry: "India",
    materialDescription: "Bamboo fork, knife, and spoon set",
    renewableMaterialPercent: 98,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: true,
    packagingMaterial: "kraft carton",
    packagingRecycledContentPercent: 45,
    packagingWeightGramsPer100Units: 54,
    productWeightGramsPer100Units: 180,
    estimatedCo2ePer1000Units: null,
    estimatedWaterLitersPer1000Units: null,
    transportMode: "sea",
    distanceKm: 7350,
    supplierDisclosureScore: 55,
    laborPolicyScore: 58,
    traceabilityScore: 44,
    evidenceStatus: "Incomplete",
    notes: "Strong natural-material story, but too much of the impact data is missing for a confident grade.",
  },
  {
    productCode: "PROD-006",
    supplierName: "BlueRoot Tableware Exports",
    productName: "BlueRoot Wooden Stirrer Pack",
    category: "CUTLERY" as ProductCategory,
    targetSegment: "Cafés and office pantry",
    unitPriceEur: 0.011,
    currency: "EUR",
    minimumOrderQuantity: 120000,
    leadTimeDays: 25,
    originCountry: "India",
    materialDescription: "Wooden coffee stirrer",
    renewableMaterialPercent: 99,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: true,
    packagingMaterial: "paper wrap",
    packagingRecycledContentPercent: 52,
    packagingWeightGramsPer100Units: 26,
    productWeightGramsPer100Units: 70,
    estimatedCo2ePer1000Units: 6.8,
    estimatedWaterLitersPer1000Units: null,
    transportMode: "sea",
    distanceKm: 7350,
    supplierDisclosureScore: 56,
    laborPolicyScore: 58,
    traceabilityScore: 49,
    evidenceStatus: "Partial proof",
    notes: "Cheap and simple, but still lacks quantified water data and stronger traceability support.",
  },
  {
    productCode: "PROD-007",
    supplierName: "CircularLeaf Goods",
    productName: "CircularLeaf Recycled Cup 12oz",
    category: "TAKEAWAY_CUPS" as ProductCategory,
    targetSegment: "Takeaway cafés and office pantry",
    unitPriceEur: 0.094,
    currency: "EUR",
    minimumOrderQuantity: 80000,
    leadTimeDays: 22,
    originCountry: "United Arab Emirates",
    materialDescription: "Recycled board cup with thin lining",
    renewableMaterialPercent: 72,
    recycledMaterialPercent: 35,
    virginPlasticPercent: 12,
    plasticLining: true,
    recyclableInPractice: false,
    industrialCompostable: false,
    homeCompostable: false,
    packagingMaterial: "corrugated carton",
    packagingRecycledContentPercent: 68,
    packagingWeightGramsPer100Units: 61,
    productWeightGramsPer100Units: 210,
    estimatedCo2ePer1000Units: 17.4,
    estimatedWaterLitersPer1000Units: 131,
    transportMode: "sea",
    distanceKm: 5200,
    supplierDisclosureScore: 61,
    laborPolicyScore: 60,
    traceabilityScore: 57,
    evidenceStatus: "Pending verification",
    notes: "Reasonable mid-market cup but lining and claim verification keep it from looking premium.",
  },
  {
    productCode: "PROD-008",
    supplierName: "CircularLeaf Goods",
    productName: "CircularLeaf Fiber Lid 90mm",
    category: "LIDS" as ProductCategory,
    targetSegment: "Cafés and premium drink service",
    unitPriceEur: 0.036,
    currency: "EUR",
    minimumOrderQuantity: 90000,
    leadTimeDays: 20,
    originCountry: "United Arab Emirates",
    materialDescription: "Molded fiber lid",
    renewableMaterialPercent: 84,
    recycledMaterialPercent: 20,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: true,
    industrialCompostable: true,
    homeCompostable: false,
    packagingMaterial: "corrugated carton",
    packagingRecycledContentPercent: 70,
    packagingWeightGramsPer100Units: 30,
    productWeightGramsPer100Units: 108,
    estimatedCo2ePer1000Units: 8.3,
    estimatedWaterLitersPer1000Units: 74,
    transportMode: "sea",
    distanceKm: 5200,
    supplierDisclosureScore: 63,
    laborPolicyScore: 60,
    traceabilityScore: 59,
    evidenceStatus: "Mixed verification",
    notes: "Good buyer-facing demo candidate if fit and compatibility notes are clear.",
  },
  {
    productCode: "PROD-009",
    supplierName: "NoordEco Supplies BV",
    productName: "NoordEco Recycled Paper Cup 8oz",
    category: "TAKEAWAY_CUPS" as ProductCategory,
    targetSegment: "Specialty cafés and office pantry",
    unitPriceEur: 0.103,
    currency: "EUR",
    minimumOrderQuantity: 25000,
    leadTimeDays: 9,
    originCountry: "Netherlands",
    materialDescription: "Recycled paper cup with thin water-based barrier",
    renewableMaterialPercent: 78,
    recycledMaterialPercent: 48,
    virginPlasticPercent: 4,
    plasticLining: true,
    recyclableInPractice: true,
    industrialCompostable: false,
    homeCompostable: false,
    packagingMaterial: "high recycled corrugated carton",
    packagingRecycledContentPercent: 91,
    packagingWeightGramsPer100Units: 50,
    productWeightGramsPer100Units: 205,
    estimatedCo2ePer1000Units: 12.7,
    estimatedWaterLitersPer1000Units: 108,
    transportMode: "road",
    distanceKm: 180,
    supplierDisclosureScore: 90,
    laborPolicyScore: 84,
    traceabilityScore: 88,
    evidenceStatus: "Verified",
    notes: "Best overall reference cup in the seed set, combining decent pricing with strong proof quality.",
  },
  {
    productCode: "PROD-010",
    supplierName: "NoordEco Supplies BV",
    productName: "NoordEco AirFiber Lid",
    category: "LIDS" as ProductCategory,
    targetSegment: "Cafés, hotels, and premium takeaway",
    unitPriceEur: 0.041,
    currency: "EUR",
    minimumOrderQuantity: 25000,
    leadTimeDays: 8,
    originCountry: "Netherlands",
    materialDescription: "Air-formed fiber lid",
    renewableMaterialPercent: 90,
    recycledMaterialPercent: 30,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: true,
    industrialCompostable: true,
    homeCompostable: false,
    packagingMaterial: "high recycled corrugated carton",
    packagingRecycledContentPercent: 93,
    packagingWeightGramsPer100Units: 24,
    productWeightGramsPer100Units: 102,
    estimatedCo2ePer1000Units: 6.5,
    estimatedWaterLitersPer1000Units: 62,
    transportMode: "road",
    distanceKm: 180,
    supplierDisclosureScore: 90,
    laborPolicyScore: 84,
    traceabilityScore: 90,
    evidenceStatus: "Verified",
    notes: "Highest-confidence lid in the prototype and a strong anchor for buyer-facing comparison views.",
  },
  {
    productCode: "PROD-011",
    supplierName: "TerraServe UK Ltd",
    productName: "TerraServe Hotel Napkin Recycled",
    category: "NAPKINS" as ProductCategory,
    targetSegment: "Hotels and office pantry",
    unitPriceEur: 0.014,
    currency: "EUR",
    minimumOrderQuantity: 50000,
    leadTimeDays: 14,
    originCountry: "United Kingdom",
    materialDescription: "Recycled-paper hospitality napkin",
    renewableMaterialPercent: 65,
    recycledMaterialPercent: 80,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: true,
    industrialCompostable: false,
    homeCompostable: false,
    packagingMaterial: "paper wrap and carton",
    packagingRecycledContentPercent: 77,
    packagingWeightGramsPer100Units: 20,
    productWeightGramsPer100Units: 62,
    estimatedCo2ePer1000Units: 4.8,
    estimatedWaterLitersPer1000Units: 39,
    transportMode: "road",
    distanceKm: 420,
    supplierDisclosureScore: 73,
    laborPolicyScore: 69,
    traceabilityScore: 64,
    evidenceStatus: "Mostly verified",
    notes: "High-commercial-promise staple product because it is inexpensive, simple, and reasonably documented.",
  },
  {
    productCode: "PROD-012",
    supplierName: "TerraServe UK Ltd",
    productName: "TerraServe Bagasse Lunch Box",
    category: "FOOD_CONTAINERS" as ProductCategory,
    targetSegment: "Office catering and lunch formats",
    unitPriceEur: 0.159,
    currency: "EUR",
    minimumOrderQuantity: 45000,
    leadTimeDays: 16,
    originCountry: "United Kingdom",
    materialDescription: "Bagasse lunch box",
    renewableMaterialPercent: 93,
    recycledMaterialPercent: 0,
    virginPlasticPercent: 0,
    plasticLining: false,
    recyclableInPractice: false,
    industrialCompostable: true,
    homeCompostable: false,
    packagingMaterial: "corrugated carton",
    packagingRecycledContentPercent: 66,
    packagingWeightGramsPer100Units: 84,
    productWeightGramsPer100Units: 430,
    estimatedCo2ePer1000Units: 20.2,
    estimatedWaterLitersPer1000Units: 198,
    transportMode: "road",
    distanceKm: 420,
    supplierDisclosureScore: 74,
    laborPolicyScore: 69,
    traceabilityScore: 67,
    evidenceStatus: "Mostly verified",
    notes: "Balanced commercial and sustainability profile for short-haul meal packaging.",
  },
];
