import type { EvidenceType, VerificationStatus } from "@prisma/client";

export const evidenceSeed: Array<{
  evidenceCode: string;
  supplierName?: string;
  productName?: string;
  type: EvidenceType;
  title: string;
  issuer: string;
  issueDate: string;
  expiryDate?: string;
  verificationStatus: VerificationStatus;
  verifiedBy?: string;
  fileName: string;
  notes: string;
  critical: boolean;
}> = [
  {
    evidenceCode: "EVD-001",
    supplierName: "EcoSip India Pvt Ltd",
    type: "CERTIFICATE",
    title: "FSC Material Declaration 2025",
    issuer: "Forest Path Verifiers",
    issueDate: "2025-02-11",
    expiryDate: "2026-02-10",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "ecosip-fsc-2025.pdf",
    notes: "Covers paper inputs used across drink-service lines.",
    critical: true,
  },
  {
    evidenceCode: "EVD-002",
    supplierName: "EcoSip India Pvt Ltd",
    type: "SOCIAL_POLICY",
    title: "Supplier Labor Policy",
    issuer: "EcoSip India Pvt Ltd",
    issueDate: "2025-03-18",
    expiryDate: "2026-03-17",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "ecosip-labor-policy.pdf",
    notes: "Adequate for prototype diligence.",
    critical: false,
  },
  {
    evidenceCode: "EVD-003",
    productName: "EcoSip Classic Paper Straw",
    type: "PRODUCT_SHEET",
    title: "Product Technical Sheet",
    issuer: "EcoSip India Pvt Ltd",
    issueDate: "2025-04-07",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "ecosip-classic-straw-spec.pdf",
    notes: "Includes weight, diameter, and composition.",
    critical: true,
  },
  {
    evidenceCode: "EVD-004",
    productName: "EcoSip Classic Paper Straw",
    type: "DECLARATION",
    title: "Compostability Statement",
    issuer: "EcoSip India Pvt Ltd",
    issueDate: "2025-04-10",
    verificationStatus: "PENDING",
    fileName: "ecosip-classic-compostability.pdf",
    notes: "Awaiting standard reference confirmation.",
    critical: true,
  },
  {
    evidenceCode: "EVD-005",
    productName: "EcoSip Bamboo Blend Straw",
    type: "PACKAGING_SPEC",
    title: "Packaging Spec Sheet",
    issuer: "EcoSip India Pvt Ltd",
    issueDate: "2025-04-12",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "ecosip-bamboo-packaging.pdf",
    notes: "Confirms carton recycled content.",
    critical: true,
  },
  {
    evidenceCode: "EVD-006",
    productName: "EcoSip Bamboo Blend Straw",
    type: "TRANSPORT_DECLARATION",
    title: "Transport Emissions Declaration",
    issuer: "EcoSip India Pvt Ltd",
    issueDate: "2025-05-02",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "ecosip-route-declaration.pdf",
    notes: "Sea route to Rotterdam lane used for demo estimate.",
    critical: false,
  },
  {
    evidenceCode: "EVD-007",
    supplierName: "FiberNest Packaging LLP",
    type: "DECLARATION",
    title: "Compostability Statement",
    issuer: "FiberNest Packaging LLP",
    issueDate: "2025-01-28",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "fibernest-compostability.pdf",
    notes: "Applies to molded-fiber bowl family.",
    critical: true,
  },
  {
    evidenceCode: "EVD-008",
    supplierName: "FiberNest Packaging LLP",
    type: "AUDIT_NOTE",
    title: "Buyer Audit Note",
    issuer: "Green2B Studio",
    issueDate: "2025-06-01",
    verificationStatus: "PENDING",
    fileName: "fibernest-audit-note.txt",
    notes: "Open point on coating disclosure.",
    critical: false,
  },
  {
    evidenceCode: "EVD-009",
    productName: "FiberNest Bagasse Bowl 750ml",
    type: "PRODUCT_SHEET",
    title: "Product Technical Sheet",
    issuer: "FiberNest Packaging LLP",
    issueDate: "2025-04-20",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "fibernest-bowl-tech-sheet.pdf",
    notes: "Includes bowl dimensions and use-case guidance.",
    critical: true,
  },
  {
    evidenceCode: "EVD-010",
    productName: "FiberNest PFAS-Free Meal Container",
    type: "DECLARATION",
    title: "PFAS-Free Declaration",
    issuer: "FiberNest Packaging LLP",
    issueDate: "2025-05-15",
    verificationStatus: "PENDING",
    fileName: "fibernest-pfas-free.pdf",
    notes: "Needs supporting lab note before buyer-facing use.",
    critical: true,
  },
  {
    evidenceCode: "EVD-011",
    supplierName: "BlueRoot Tableware Exports",
    type: "SOCIAL_POLICY",
    title: "Supplier Labor Policy",
    issuer: "BlueRoot Tableware Exports",
    issueDate: "2024-11-05",
    expiryDate: "2025-11-04",
    verificationStatus: "EXPIRED",
    fileName: "blueroot-labor-policy.pdf",
    notes: "Expired and needs refresh.",
    critical: false,
  },
  {
    evidenceCode: "EVD-012",
    productName: "BlueRoot Bamboo Cutlery Set",
    type: "PRODUCT_SHEET",
    title: "Product Technical Sheet",
    issuer: "BlueRoot Tableware Exports",
    issueDate: "2025-02-02",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "blueroot-cutlery-tech-sheet.pdf",
    notes: "No quantified footprint data attached.",
    critical: true,
  },
  {
    evidenceCode: "EVD-013",
    productName: "BlueRoot Bamboo Cutlery Set",
    type: "LCA_LITE",
    title: "LCA-Lite Placeholder",
    issuer: "BlueRoot Tableware Exports",
    issueDate: "2025-02-10",
    verificationStatus: "MISSING_CRITICAL",
    fileName: "blueroot-cutlery-lca-lite.pdf",
    notes: "Supplier promised but has not supplied usable data.",
    critical: true,
  },
  {
    evidenceCode: "EVD-014",
    productName: "BlueRoot Wooden Stirrer Pack",
    type: "DECLARATION",
    title: "Wood Source Attestation",
    issuer: "BlueRoot Tableware Exports",
    issueDate: "2025-01-14",
    verificationStatus: "PENDING",
    fileName: "blueroot-wood-attestation.pdf",
    notes: "Needs third-party basis or stronger traceability context.",
    critical: true,
  },
  {
    evidenceCode: "EVD-015",
    supplierName: "CircularLeaf Goods",
    type: "CERTIFICATE",
    title: "FSC-Like Supplier Claim",
    issuer: "CircularLeaf Goods",
    issueDate: "2025-03-11",
    verificationStatus: "PENDING",
    fileName: "circularleaf-fsc-claim.pdf",
    notes: "Buyer-facing use should wait for verification.",
    critical: true,
  },
  {
    evidenceCode: "EVD-016",
    productName: "CircularLeaf Recycled Cup 12oz",
    type: "PACKAGING_SPEC",
    title: "Packaging Spec Sheet",
    issuer: "CircularLeaf Goods",
    issueDate: "2025-03-23",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "circularleaf-cup-packaging.pdf",
    notes: "Confirms carton recycled content.",
    critical: true,
  },
  {
    evidenceCode: "EVD-017",
    productName: "CircularLeaf Fiber Lid 90mm",
    type: "PRODUCT_SHEET",
    title: "Product Technical Sheet",
    issuer: "CircularLeaf Goods",
    issueDate: "2025-03-26",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "circularleaf-lid-tech-sheet.pdf",
    notes: "Useful for fit and weight confirmation.",
    critical: true,
  },
  {
    evidenceCode: "EVD-018",
    supplierName: "NoordEco Supplies BV",
    type: "CERTIFICATE",
    title: "B Corp Certificate",
    issuer: "B Lab",
    issueDate: "2025-01-02",
    expiryDate: "2026-01-01",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "noordeco-bcorp.pdf",
    notes: "Current and verified.",
    critical: false,
  },
  {
    evidenceCode: "EVD-019",
    supplierName: "NoordEco Supplies BV",
    type: "CERTIFICATE",
    title: "FSC Material Declaration 2025",
    issuer: "Forest Path Verifiers",
    issueDate: "2025-01-19",
    expiryDate: "2026-01-18",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "noordeco-fsc-2025.pdf",
    notes: "Current and cleanly documented.",
    critical: true,
  },
  {
    evidenceCode: "EVD-020",
    productName: "NoordEco Recycled Paper Cup 8oz",
    type: "PRODUCT_SHEET",
    title: "Product Technical Sheet",
    issuer: "NoordEco Supplies BV",
    issueDate: "2025-04-03",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "noordeco-cup-tech-sheet.pdf",
    notes: "Full dimensions and barrier note.",
    critical: true,
  },
  {
    evidenceCode: "EVD-021",
    productName: "NoordEco Recycled Paper Cup 8oz",
    type: "TRANSPORT_DECLARATION",
    title: "Transport Emissions Declaration",
    issuer: "NoordEco Supplies BV",
    issueDate: "2025-04-05",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "noordeco-road-route.pdf",
    notes: "Short-haul Dutch distribution route.",
    critical: false,
  },
  {
    evidenceCode: "EVD-022",
    productName: "NoordEco AirFiber Lid",
    type: "PACKAGING_SPEC",
    title: "Packaging Spec Sheet",
    issuer: "NoordEco Supplies BV",
    issueDate: "2025-04-09",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "noordeco-lid-packaging.pdf",
    notes: "Strong packaging proof pack.",
    critical: true,
  },
  {
    evidenceCode: "EVD-023",
    supplierName: "TerraServe UK Ltd",
    type: "DECLARATION",
    title: "Packaging Declaration Set",
    issuer: "TerraServe UK Ltd",
    issueDate: "2025-02-20",
    verificationStatus: "VERIFIED",
    verifiedBy: "M. Verbeek",
    fileName: "terraserve-packaging-set.pdf",
    notes: "Covers carton and primary-pack disclosures.",
    critical: false,
  },
  {
    evidenceCode: "EVD-024",
    productName: "TerraServe Hotel Napkin Recycled",
    type: "CERTIFICATE",
    title: "Recycled Fiber Declaration",
    issuer: "TerraServe UK Ltd",
    issueDate: "2025-03-01",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "terraserve-napkin-recycled.pdf",
    notes: "Sufficient for buyer demo usage.",
    critical: true,
  },
  {
    evidenceCode: "EVD-025",
    productName: "TerraServe Bagasse Lunch Box",
    type: "PRODUCT_SHEET",
    title: "Product Technical Sheet",
    issuer: "TerraServe UK Ltd",
    issueDate: "2025-03-04",
    verificationStatus: "VERIFIED",
    verifiedBy: "L. Janssen",
    fileName: "terraserve-lunchbox-tech-sheet.pdf",
    notes: "Complete enough for product comparison view.",
    critical: true,
  },
  {
    evidenceCode: "EVD-026",
    productName: "TerraServe Bagasse Lunch Box",
    type: "DECLARATION",
    title: "Food Contact Declaration",
    issuer: "TerraServe UK Ltd",
    issueDate: "2025-03-07",
    verificationStatus: "PENDING",
    fileName: "terraserve-food-contact.pdf",
    notes: "Pending final analyst review.",
    critical: true,
  },
];
